const mysql = require('mysql');
const util = require('util');
const conn = mysql.createConnection({
  host: 'localhost', user: 'root', password: '%Xlr8-1997$', database: 'onsv'
});
const q = util.promisify(conn.query).bind(conn);

const valoresES = "<p>Actuamos con \u00e9tica, honestidad y coherencia en la gesti\u00f3n de la informaci\u00f3n p\u00fablica. Creemos en la transparencia, el compromiso, la vocaci\u00f3n de servicio, el trabajo articulado y la innovaci\u00f3n para reducir la siniestralidad y proteger la vida de las personas en las v\u00edas.</p><div class=\"valores-grid\"><div class=\"valores-card\" style=\"border-left-color:#dc2626;\"><h3>INTEGRIDAD</h3><p>Actuamos con \u00e9tica, honestidad y coherencia en la gesti\u00f3n de la informaci\u00f3n p\u00fablica.</p></div><div class=\"valores-card\" style=\"border-left-color:#2563eb;\"><h3>TRANSPARENCIA</h3><p>Promovemos el acceso abierto a datos confiables de seguridad vial para toda la ciudadan\u00eda.</p></div><div class=\"valores-card\" style=\"border-left-color:#0ea5e9;\"><h3>COMPROMISO</h3><p>Trabajamos por reducir la siniestralidad y proteger la vida de las personas en las v\u00edas.</p></div><div class=\"valores-card\" style=\"border-left-color:#16a34a;\"><h3>VOCACI\u00d3N DE SERVICIO</h3><p>Orientamos nuestro esfuerzo a las necesidades de las instituciones y de la poblaci\u00f3n.</p></div><div class=\"valores-card\" style=\"border-left-color:#eab308;\"><h3>TRABAJO ARTICULADO</h3><p>Fomentamos la coordinaci\u00f3n intersectorial e intergubernamental basada en evidencia.</p></div><div class=\"valores-card\" style=\"border-left-color:#7e22ce;\"><h3>INNOVACI\u00d3N</h3><p>Incorporamos tecnolog\u00eda y an\u00e1lisis de datos para una mejor toma de decisiones.</p></div></div>";

const valoresEN = "<p>We act with ethics, honesty and consistency in the management of public information. We believe in transparency, commitment, service vocation, articulated work and innovation to reduce road crashes and protect lives on the roads.</p><div class=\"valores-grid\"><div class=\"valores-card\" style=\"border-left-color:#dc2626;\"><h3>INTEGRITY</h3><p>We act with ethics, honesty and consistency in the management of public information.</p></div><div class=\"valores-card\" style=\"border-left-color:#2563eb;\"><h3>TRANSPARENCY</h3><p>We promote open access to reliable road safety data for all citizens.</p></div><div class=\"valores-card\" style=\"border-left-color:#0ea5e9;\"><h3>COMMITMENT</h3><p>We work to reduce road crashes and protect people's lives on the roads.</p></div><div class=\"valores-card\" style=\"border-left-color:#16a34a;\"><h3>SERVICE VOCATION</h3><p>We focus our efforts on the needs of institutions and the population.</p></div><div class=\"valores-card\" style=\"border-left-color:#eab308;\"><h3>ARTICULATED WORK</h3><p>We foster intersectoral and intergovernmental coordination based on evidence.</p></div><div class=\"valores-card\" style=\"border-left-color:#7e22ce;\"><h3>INNOVATION</h3><p>We incorporate technology and data analysis for better decision making.</p></div></div>";

const compES = "<h1 class=\"tech-title\">COMPONENTES TECNOL\u00d3GICOS</h1><div class=\"tech-grid\"><div class=\"tech-card\" style=\"border-left-color:#dc2626;\"><div class=\"tech-icon\" style=\"background:#fde2e2;color:#dc2626;\"><svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\" ry=\"2\"></rect><line x1=\"8\" y1=\"21\" x2=\"16\" y2=\"21\"></line><line x1=\"12\" y1=\"17\" x2=\"12\" y2=\"21\"></line></svg></div><h3>SISTEMA DE INFORMACI\u00d3N DE SINIESTROS</h3><p>Estandariza las variables para el recojo y registro de informaci\u00f3n ante la ocurrencia de un siniestro, sobre la base del Formato \u00danico de Registro de Accidentes de Tr\u00e1nsito (RD N\u00b0 020-2019-MTC/18).</p></div><div class=\"tech-card\" style=\"border-left-color:#2563eb;\"><div class=\"tech-icon\" style=\"background:#dbeafe;color:#2563eb;\"><svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z\"></path><circle cx=\"12\" cy=\"10\" r=\"3\"></circle></svg></div><h3>VISOR GEORREFERENCIADO</h3><p>Permite visualizar al p\u00fablico y a las entidades de rescate el lugar exacto del siniestro de tr\u00e1nsito.</p></div><div class=\"tech-card\" style=\"border-left-color:#0ea5e9;\"><div class=\"tech-icon\" style=\"background:#e0f2fe;color:#0284c7;\"><svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"23 6 13.5 15.5 8.5 10.5 1 18\"></polyline><polyline points=\"17 6 23 6 23 12\"></polyline></svg></div><h3>ANAL\u00cdTICA DE DATOS</h3><p>Permite interactuar con los indicadores de seguridad vial de cada localidad mediante herramientas de business intelligence.</p></div><div class=\"tech-card\" style=\"border-left-color:#16a34a;\"><div class=\"tech-icon\" style=\"background:#d1fae5;color:#059669;font-weight:700;font-size:18px;\">T</div><h3>PORTAL WEB</h3><p>Orientado a una pol\u00edtica de datos abiertos a fin de fomentar la investigaci\u00f3n en materia de seguridad vial.</p></div></div>";

const compEN = "<h1 class=\"tech-title\">TECHNOLOGICAL COMPONENTS</h1><div class=\"tech-grid\"><div class=\"tech-card\" style=\"border-left-color:#dc2626;\"><div class=\"tech-icon\" style=\"background:#fde2e2;color:#dc2626;\"><svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\" ry=\"2\"></rect><line x1=\"8\" y1=\"21\" x2=\"16\" y2=\"21\"></line><line x1=\"12\" y1=\"17\" x2=\"12\" y2=\"21\"></line></svg></div><h3>CRASH INFORMATION SYSTEM</h3><p>Standardizes variables for collecting and recording information when a crash occurs, based on the Single Traffic Accident Record Format (RD N\u00b0 020-2019-MTC/18).</p></div><div class=\"tech-card\" style=\"border-left-color:#2563eb;\"><div class=\"tech-icon\" style=\"background:#dbeafe;color:#2563eb;\"><svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z\"></path><circle cx=\"12\" cy=\"10\" r=\"3\"></circle></svg></div><h3>GEOREFERENCED VIEWER</h3><p>Allows the public and rescue entities to visualize the exact location of the traffic crash.</p></div><div class=\"tech-card\" style=\"border-left-color:#0ea5e9;\"><div class=\"tech-icon\" style=\"background:#e0f2fe;color:#0284c7;\"><svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"23 6 13.5 15.5 8.5 10.5 1 18\"></polyline><polyline points=\"17 6 23 6 23 12\"></polyline></svg></div><h3>DATA ANALYTICS</h3><p>Enables interaction with road safety indicators for each locality through business intelligence tools.</p></div><div class=\"tech-card\" style=\"border-left-color:#16a34a;\"><div class=\"tech-icon\" style=\"background:#d1fae5;color:#059669;font-weight:700;font-size:18px;\">T</div><h3>WEB PORTAL</h3><p>Aimed at an open data policy to promote research in road safety.</p></div></div>";

(async () => {
  try {
    await q("UPDATE pagina SET seccion4 = ? WHERE idioma = 'ES'", [compES]);
    await q("UPDATE pagina SET seccion4 = ? WHERE idioma = 'EN'", [compEN]);
    await q("UPDATE pagina SET seccion5 = ? WHERE idioma = 'ES'", [valoresES]);
    await q("UPDATE pagina SET seccion5 = ? WHERE idioma = 'EN'", [valoresEN]);
    console.log('Seed completado');
    const r = await q("SELECT idioma, LENGTH(seccion4) s4len, LENGTH(seccion5) s5len FROM pagina");
    console.log(JSON.stringify(r, null, 2));
  } catch (e) { console.error(e); }
  conn.end();
})();
