USE onsv;

ALTER TABLE pagina
	ADD COLUMN seccion36 VARCHAR(500) NULL COMMENT 'Comp1 link',
	ADD COLUMN seccion37 VARCHAR(500) NULL COMMENT 'Comp2 link',
	ADD COLUMN seccion38 VARCHAR(500) NULL COMMENT 'Comp3 link',
	ADD COLUMN seccion39 VARCHAR(500) NULL COMMENT 'Comp4 link',
	ADD COLUMN seccion40 VARCHAR(500) NULL COMMENT 'Comp5 link',
	ADD COLUMN seccion41 VARCHAR(500) NULL COMMENT 'Comp6 link',
	ADD COLUMN seccion42 VARCHAR(500) NULL COMMENT 'Comp7 link',
	ADD COLUMN seccion43 VARCHAR(500) NULL COMMENT 'Comp8 link',
	ADD COLUMN seccion44 VARCHAR(500) NULL COMMENT 'Comp9 link';
