$axure.loadCurrentPage({
  "url":"page_1.html",
  "generationDate":new Date(1751897626529.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"57668408a5e14047813eb0dfd6f0b0ad",
    "type":"Axure:Page",
    "name":"Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"far",
      "imageVerticalAlignment":"far",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"5",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4322db3d7f1543d3a162aebb78022197",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":2},
            "size":{
              "width":1168,
              "height":127}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50ba5b118eb44934a20fa546e4126bb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":2},
                "size":{
                  "width":1168,
                  "height":127}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u0.png"}},
{
          "id":"75e1b0f67280461e9511c262e6205f5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":546,
              "y":67},
            "size":{
              "width":429,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc6e9436837848d4977ee5baa7933cf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":546,
                  "y":67},
                "size":{
                  "width":429,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u2.png"}},
{
          "id":"2baa3acafb0141fc960ac21012408ce8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":985,
              "y":65},
            "size":{
              "width":201,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a56a65f8b00a4fac8b702e14f30c467e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":985,
                  "y":65},
                "size":{
                  "width":201,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u4.png"}},
{
          "id":"f5fdaae836274486a5bffe1f70e640a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1185,
              "y":71},
            "size":{
              "width":165,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a4a95dbd5c3415a8395791f0234f2b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1185,
                  "y":71},
                "size":{
                  "width":165,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u6.png"}},
{
          "id":"1d7b55558a5340c781157255a4d2d825",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrita', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":216,
              "y":142},
            "size":{
              "width":1168,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fc19bc1067442a8b788a09d4347e560",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrita', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":216,
                  "y":142},
                "size":{
                  "width":1168,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u8.png"}},
{
          "id":"da09a974ca434dfaa1b7ff294cc75c5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":197},
            "size":{
              "width":1168,
              "height":372}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be070a63a0a44c2e95142d9a2e1803c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":197},
                "size":{
                  "width":1168,
                  "height":372}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u10.png"}},
{
          "id":"baa3affbc5e1493683784377c0d1dc38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":572},
            "size":{
              "width":1168,
              "height":317}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6387ce823db64f4abe14ce319f49b718",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":572},
                "size":{
                  "width":1168,
                  "height":317}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u12.png"}},
{
          "id":"619f4320f62d440a91920689c04502ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":889},
            "size":{
              "width":1178,
              "height":212}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"949b2e77932c49d9bd1fe6d90645de45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":889},
                "size":{
                  "width":1178,
                  "height":212}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u14.png"}},
{
          "id":"74c6155cec6e496395d61fd4e86fa597",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":1095},
            "size":{
              "width":1160,
              "height":525}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b4b67086159432eb5ce0f12683cd6cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":1095},
                "size":{
                  "width":1160,
                  "height":525}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u16.png"}},
{
          "id":"7251d4ea7fa244f39d379861e63f8193",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":1614},
            "size":{
              "width":1150,
              "height":347}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dfaa30f8cd244099263b2e07e09aff2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":1614},
                "size":{
                  "width":1150,
                  "height":347}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"377035ba321b411b85d415ee2f7e6367",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":2377},
            "size":{
              "width":1150,
              "height":394}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85032b5795d24a58b5d273b731a50715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":2377},
                "size":{
                  "width":1150,
                  "height":394}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u20.png"}},
{
          "id":"04498d7a26634ec8a52ac7bd38c7b182",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":2779},
            "size":{
              "width":1160,
              "height":623}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e6729f8c74340b8b85f7ce672d7a84e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":2779},
                "size":{
                  "width":1160,
                  "height":623}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u22.png"}},
{
          "id":"82db25a8ad0140949b057929fbb7d607",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":3414},
            "size":{
              "width":1143,
              "height":212}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f596796c59649ec9d299bdcdc0f8989",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":207,
                  "y":3414},
                "size":{
                  "width":1143,
                  "height":212}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u24.png"}},
{
          "id":"2487a72a2b2d4c43b72f6532999d39ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":3627},
            "size":{
              "width":1134,
              "height":179}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1b6b5d636d44d71ad33c89b9d0b36de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":3627},
                "size":{
                  "width":1134,
                  "height":179}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u26.png"}},
{
          "id":"ff3c84da8bb843e9a78c4cf8e75725f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":3814},
            "size":{
              "width":1134,
              "height":198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4614e3a592b4d60bdd23166937e0d08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":3814},
                "size":{
                  "width":1134,
                  "height":198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u28.png"}},
{
          "id":"fa06c83523ad4cc29d479408201b6dae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":1961},
            "size":{
              "width":1150,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"272734f04feb49899e8701941f2a85cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":1961},
                "size":{
                  "width":1150,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u30.png"}},
{
          "id":"fd1ec89b3f5c4ccdb08694c5c8b19690",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1456,
              "y":572},
            "size":{
              "width":52,
              "height":187}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"226510985ddd41a8963c438ec9af72c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1456,
                  "y":572},
                "size":{
                  "width":52,
                  "height":187}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u32.png"}},
{
          "id":"41a87dd74a74405fb443b561d2d78e29",
          "label":"",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":153},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "repeaterPropMap":{
            "isolateRadio":false,
            "isolateSelection":false,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":130,
              "height":30,
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}}},
          "objects":[{
              "id":"0ecf47d8c9e0452c906ed09e09d51fbf",
              "label":"",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrita', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF585856},
                "size":{
                  "width":130,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d068db7ecb3549e5b344b980cb575f7f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negrita', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF585856},
                    "size":{
                      "width":130,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open Page 2 in Current Window",
                          "target":{
                            "targetType":"page",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/page_1/u35.png"}}],
          "data":[{
              "column0":{
                "type":"page",
                "text":"Page 2"}}],
          "dataProps":["column0"]},
{
          "id":"c108e09aaaba413895e266ea4d94d67d",
          "label":"",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":165},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":20,
              "height":10,
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}}},
          "objects":[{
              "id":"5789afdf80cd45f8854a6cac244c456a",
              "label":"",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05a0b3b969d144c89902e997ff4d590a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open Page 1 in Current Window",
                          "target":{
                            "targetType":"page",
                            "url":"page_1.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/page_1/u38.png"}}],
          "data":[{
              "column0":{
                "type":"page",
                "text":"Page 1",
                "url":"page_1.html"}}],
          "dataProps":["column0"]}]}},
  "masters":{
},
  "objectPaths":{
    "4322db3d7f1543d3a162aebb78022197":{
      "scriptId":"u0"},
    "50ba5b118eb44934a20fa546e4126bb0":{
      "scriptId":"u1"},
    "75e1b0f67280461e9511c262e6205f5d":{
      "scriptId":"u2"},
    "cc6e9436837848d4977ee5baa7933cf1":{
      "scriptId":"u3"},
    "2baa3acafb0141fc960ac21012408ce8":{
      "scriptId":"u4"},
    "a56a65f8b00a4fac8b702e14f30c467e":{
      "scriptId":"u5"},
    "f5fdaae836274486a5bffe1f70e640a9":{
      "scriptId":"u6"},
    "4a4a95dbd5c3415a8395791f0234f2b9":{
      "scriptId":"u7"},
    "1d7b55558a5340c781157255a4d2d825":{
      "scriptId":"u8"},
    "9fc19bc1067442a8b788a09d4347e560":{
      "scriptId":"u9"},
    "da09a974ca434dfaa1b7ff294cc75c5f":{
      "scriptId":"u10"},
    "be070a63a0a44c2e95142d9a2e1803c6":{
      "scriptId":"u11"},
    "baa3affbc5e1493683784377c0d1dc38":{
      "scriptId":"u12"},
    "6387ce823db64f4abe14ce319f49b718":{
      "scriptId":"u13"},
    "619f4320f62d440a91920689c04502ba":{
      "scriptId":"u14"},
    "949b2e77932c49d9bd1fe6d90645de45":{
      "scriptId":"u15"},
    "74c6155cec6e496395d61fd4e86fa597":{
      "scriptId":"u16"},
    "8b4b67086159432eb5ce0f12683cd6cc":{
      "scriptId":"u17"},
    "7251d4ea7fa244f39d379861e63f8193":{
      "scriptId":"u18"},
    "4dfaa30f8cd244099263b2e07e09aff2":{
      "scriptId":"u19"},
    "377035ba321b411b85d415ee2f7e6367":{
      "scriptId":"u20"},
    "85032b5795d24a58b5d273b731a50715":{
      "scriptId":"u21"},
    "04498d7a26634ec8a52ac7bd38c7b182":{
      "scriptId":"u22"},
    "9e6729f8c74340b8b85f7ce672d7a84e":{
      "scriptId":"u23"},
    "82db25a8ad0140949b057929fbb7d607":{
      "scriptId":"u24"},
    "5f596796c59649ec9d299bdcdc0f8989":{
      "scriptId":"u25"},
    "2487a72a2b2d4c43b72f6532999d39ff":{
      "scriptId":"u26"},
    "a1b6b5d636d44d71ad33c89b9d0b36de":{
      "scriptId":"u27"},
    "ff3c84da8bb843e9a78c4cf8e75725f8":{
      "scriptId":"u28"},
    "c4614e3a592b4d60bdd23166937e0d08":{
      "scriptId":"u29"},
    "fa06c83523ad4cc29d479408201b6dae":{
      "scriptId":"u30"},
    "272734f04feb49899e8701941f2a85cd":{
      "scriptId":"u31"},
    "fd1ec89b3f5c4ccdb08694c5c8b19690":{
      "scriptId":"u32"},
    "226510985ddd41a8963c438ec9af72c6":{
      "scriptId":"u33"},
    "41a87dd74a74405fb443b561d2d78e29":{
      "scriptId":"u34"},
    "0ecf47d8c9e0452c906ed09e09d51fbf":{
      "scriptId":"u35"},
    "d068db7ecb3549e5b344b980cb575f7f":{
      "scriptId":"u36"},
    "c108e09aaaba413895e266ea4d94d67d":{
      "scriptId":"u37"},
    "5789afdf80cd45f8854a6cac244c456a":{
      "scriptId":"u38"},
    "05a0b3b969d144c89902e997ff4d590a":{
      "scriptId":"u39"}}});